### ISSUE TITLE
Как реализовать обращение к вершинам

### ISSUE THREAD

**Issue by kstrizhov** [kstrizhov/treegrapher#6]
@aurusov 
Я написал класс Node в начальном варианте, но возник вопрос, как обращаться к вершинам. Все вершины создаются после обращения в функции TreeGr() к методу MakeChildren() (строчка 78 в /src/tree_grapher/TreeGr.java). Как я это вижу, объекты локальные относительно метода, создаются внутри него и удаляются после выхода.
Если я правильно все изложил выше, то обратиться напрямую после вызова MakeChildren() к вершинам\нодам будет нельзя. 

Как можно выйти из ситуации?

**Comment by kstrizhov** [comment]
Я вроде разобрался, обращаюсь через корень дерева, получилось таким образом раскрасить вершины.

**Comment by aurusov** [comment]
1. Локальных объектов в джаве нет, удаляет их сборщик мусора
2. Надо научиться по любой вершине получать рута, а не так как тут https://github.com/kstrizhov/treegrapher/blob/master/src/tree_grapher/TreeGr.java#L115 (или из mxGraph или из mxCell)
3. Задал вопрос про `MakeRootNode` - должно было прийти уведомление

**Comment by kstrizhov** [comment]
Получить корень легко, спрашивать предка до тех пор, пока не получим вершину, у которой нулевой предок. Я не понимаю, как например обратиться к созданной в `MakeChildren` вершине, полученной в i-той итерации. Не вижу способа сделать это напрямую.

С другой стороны, зная объект Node рута, мы можем получить mxCell любого потомка, и наоборот. Например, это реализовано в методе `colorNodes`.

**Comment by aurusov** [comment]
> Я не понимаю, как например обратиться к созданной в MakeChildren вершине, полученной в i-той итерации.

Надо решить задачу получения `Node` по клику на `mxCell`. Ты понимаешь зачем это надо и как это решить ? А то из цитаты следует, что нет, или я её не так понял.

**Comment by kstrizhov** [comment]
Это я понимаю, для этого можно вызвать метод `mxCell.getValue()` и присвоить объекту типа `Node`.

**Comment by aurusov** [comment]
Хорошо. Тогда поясни цитату.

**Comment by kstrizhov** [comment]
Я не вижу возможности обращаться напрямую к созданным объектам child в методе `MakeChildren`. То есть на первой итерации создается объект child, на второй итерации создается объект с таким же именем, и тд. И получается, что различить их можно только по нодам, которые передаем через `setValue`. Поэтому все операции приходится производить через Node рута.

**Comment by aurusov** [comment]
Где тебе их надо еще различать ? Вижу только один случай - выделение мышкой. По клику на вершину ты будешь получать mxCell (я так надеюсь, хотя уже ничему не удивлюсь в этой либе). И только потом получишь `node = getCell()->getValue()` (псевдокод). В каких случаях и зачем тебе mxCell ?
